### ISSUE TITLE
CR: Self recording and transcribing platform in pecha tool

### ISSUE THREAD

**Issue by Tech-lo** [OpenPecha/Voice-Scribe#1]
## Title
Pecha-tool-for-vocal-script
## Description
We need a Pecha tool where a user can self-record their audio on any topic and also transcribe text from the audio.

## Expected UI
![Image](https://github.com/user-attachments/assets/1ebe510a-c26b-41e2-9a9e-1fdd80cc2514)

audio recording time limit 1:30 min

## Sub-tasks

- [x] Create a remix app 
    - [x] UI Design and Implementation
- [x] make the connection with db using Prisma
- [x] Define Prisma models for Recording and User
- [x] generate loader and pass initial annotator data from it to the UI
- [x] generate action to get data from inputs and update it on the database
- [x] Make a sidebar to view the history of work done by annotators and reviewers
- [x] user list in admin needs role changing option 
- [x] reviewer UI (same as annotator with editing but original transcript saved from annotator will remain same and the updated one will be in reviewed_transcript field, only  accept or rejects, and when rejected, move to TRASH status)

extra note:
user should be able to log in by going to /?session={email}
eg.   http://localhost:8000/?session=tashi@gmail.com

## Card reviewer
- [x] @tentamdin

**Comment by tenkus47** [comment]
@Tech-lo  i have updated the  Steps please do update it if needed, @tentamdin  please review the card and make any required changes .

**Comment by kaldan007** [comment]
reviewer UI:
![Image](https://github.com/user-attachments/assets/a137151a-855b-49f0-9c86-250f6633ca2c)

**Comment by kaldan007** [comment]
@Tech-lo can u deploy and add me for testing under kaldan@esukhia.org

**Comment by kaldan007** [comment]
@Tech-lo 
- add monlam font
- increase font size to 20
- need play button on history list item
- update responsiveness

**Comment by Tech-lo** [comment]
Additional Requirements(from product owner):
- Set a 12-second limit for audio recordings.
- Reduce the size of the audio player for better usability.
- Allow users to record multiple audio clips and submit them. Submission should be based on the completed recordings, and transcription will be done afterward. (Current flow requires both audio and transcript to be filled out before submission.)(from product owner but he is not user and the flow will be changed if so)
- Enhance the existing admin reports to include details metrics such as task progress, time spent and activity logs for each user.
- Display real-time recording time during audio recording, so users can track the start and end time of their recordings.
